data:
  batch_size: 128
  datapath: ~/Datasets/CIFAR
  dataset: cifar10
  workers: 4
description: ''
mia:
  attack_type: lira
  enabled: false
  num_shadow_models: 64
  recalibrate: false
  shadow_epochs: 200
model:
  arch: resnet
  depth_mult: 1.0
  layers: 20
  model_mult: 0
  width_mult: 1.0
name: dwa_reactivate_only_alpha0.5_beta0.5_sparsity_0.95_cifar10_resnet
pruning:
  dwa_alpha: 0.5
  dwa_beta: 0.5
  dwa_mode: reactivate_only
  dwa_threshold_percentile: 50
  enabled: true
  freeze_epoch: -1
  importance_method: L1
  method: dcil
  prune_freq: 16
  prune_type: unstructured
  sparsity: 0.95
  target_epoch: 75
save_dir: runs/dwa/reactivate_only/sparsity_0.95/cifar10/alpha0.5_beta0.5
system:
  benchmark: true
  deterministic: true
  gpu: 0
  print_freq: 100
  save_freq: 10
  seed: 42
training:
  epochs: 200
  gamma: 0.1
  lr: 0.1
  milestones:
  - 100
  - 150
  momentum: 0.9
  nesterov: false
  scheduler: multistep
  step_size: 30
  warmup_loss_epoch: 70
  warmup_lr: 0.1
  warmup_lr_epoch: 0
  weight_decay: 0.0005
wandb:
  enabled: true
  entity: null
  name: dwa_reactivate_only_alpha0.5_beta0.5_sparsity_0.95_cifar10_resnet
  notes: ''
  project: prunig_dwa_grad
  tags:
  - dwa
  - reactivate_only
  - cifar10
  - resnet
