version: '3.8'

services:
  pruning-mia:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1
      - CUDA_VISIBLE_DEVICES=0,1
    volumes:
      # Mount the current project directory
      - .:/workspace
      # Mount the CIFAR dataset directory
      - /home/user/Desktop/solhee/Datasets/CIFAR:/workspace/data
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]