name: dcil-mia-experiment
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9.18
  
  # PyTorch ecosystem (CUDA 11.8 compatible)
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pytorch-cuda=11.8
  
  # Core scientific computing
  - numpy=1.24.4
  - scipy=1.11.3
  - pandas=2.1.1
  
  # Visualization and plotting
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - plotly=5.17.0
  
  # Machine learning and statistics
  - scikit-learn=1.3.1
  
  # Utilities
  - tqdm=4.66.1
  - psutil=5.9.5
  - pyyaml=6.0.1
  - joblib=1.3.2
  
  # Image processing
  - pillow=10.0.1
  - opencv=4.8.1
  
  # Development and analysis tools
  - jupyter=1.0.0
  - notebook=7.0.6
  - ipykernel=6.25.2
  
  # Code quality
  - black=23.9.1
  - flake8=6.1.0
  
  # System tools
  - git=2.42.0
  
  # Additional dependencies for the experiment
  - h5py=3.9.0
  - hdf5=1.14.2
  - networkx=3.2
  
  # pip packages
  - pip=23.3
  - pip:
    # Experiment tracking (optional)
    - tensorboard>=2.14.0
    - wandb>=0.15.12
    
    # Additional ML utilities
    - torchsummary>=1.5.1
    - thop>=0.1.1  # for FLOPs calculation
    
    # Enhanced plotting
    - plotly-express>=0.4.1
    - kaleido>=0.2.1  # for plotly image export
    
    # Configuration management
    - omegaconf>=2.3.0
    
    # Memory profiling
    - memory-profiler>=0.61.0
    
    # Progress visualization
    - rich>=13.6.0