data:
  batch_size: 128
  datapath: ~/Datasets/CIFAR
  dataset: cifar10
  workers: 4
description: ''
mia:
  attack_type: lira
  enabled: false
  num_shadow_models: 64
  recalibrate: false
  shadow_epochs: 200
model:
  arch: resnet
  depth_mult: 1.0
  layers: 20
  model_mult: 0
  width_mult: 1.0
name: dwa_kill_active_plain_dead_sparsity_0.8_cifar10_resnet
pruning:
  enabled: true
  freeze_epoch: -1
  importance_method: L1
  method: dpf
  prune_freq: 16
  prune_type: unstructured
  sparsity: 0.8
  target_epoch: 75
save_dir: runs/dwa/kill_active_plain_dead/sparsity_0.8/cifar10
system:
  benchmark: true
  deterministic: true
  gpu: 0
  print_freq: 100
  save_freq: 10
  seed: 42
training:
  epochs: 200
  gamma: 0.1
  lr: 0.1
  milestones:
  - 100
  - 150
  momentum: 0.9
  nesterov: false
  scheduler: multistep
  step_size: 30
  warmup_loss_epoch: 70
  warmup_lr: 0.1
  warmup_lr_epoch: 0
  weight_decay: 0.0005
wandb:
  enabled: true
  entity: null
  name: dwa_kill_active_plain_dead_sparsity_0.8_cifar10_resnet
  notes: ''
  project: pruning_dwa
  tags:
  - dwa
  - all-sparsity
  - dwa
  - kill_active_plain_dead
  - cifar10
  - resnet
